name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-14, ubuntu-24.04-arm, macos-13, windows-2022]
        build_type: [Release]
        staticcompile: [ON]

    steps:
    - uses: actions/checkout@v4.1.1

    # install dependencies
    - name: Configure CMake for linux
      if: contains(matrix.os, 'ubuntu')
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_TESTING=ON  -DSTATICCOMPILE=${{ matrix.staticcompile }}

    - name: Configure CMake for non-linux
      if: contains(matrix.os, 'macos') || contains(matrix.os, 'windows')
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_TESTING=OFF -DSTATICCOMPILE=${{ matrix.staticcompile }}

    - name: Build
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      run: ctest -C ${{ matrix.build_type }}

    - name: Upload Artifact - Linux x86_64
      if: contains(matrix.os, 'ubuntu') && !contains(matrix.os, 'arm') && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: sbva-linux-amd64
        path: sbva

    - name: Upload Artifact - Linux arm64
      if: contains(matrix.os, 'ubuntu') && contains(matrix.os, 'arm') && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: sbva-linux-arm64
        path: sbva

    - name: Upload Artifact - Mac x86_64
      if: matrix.os == 'macos-13' && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: sbva-mac-x86_64
        path: sbva

    - name: Upload Artifact - Mac arm64
      if: matrix.os == 'macos-14' && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: sbva-mac-arm64
        path: sbva

    - name: Upload Artifact - Windows
      if: matrix.os == 'windows-2022' && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: sbva-win64.exe
        path: Release\sbva.exe
